using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Text;
using LogicGamer.Core.Attributes;

namespace LogicGamer.Core
{
    public static  class GeneratorTool
    {
        private static readonly Dictionary<string, string> TypeAliases = new()
        {
            ["System.Void"] = "void",
            ["System.Boolean"] = "bool",
            ["System.Byte"] = "byte",
            ["System.SByte"] = "sbyte",
            ["System.Char"] = "char",
            ["System.Decimal"] = "decimal",
            ["System.Double"] = "double",
            ["System.Single"] = "float",
            ["System.Int32"] = "int",
            ["System.UInt32"] = "uint",
            ["System.Int64"] = "long",
            ["System.UInt64"] = "ulong",
            ["System.Object"] = "object",
            ["System.Int16"] = "short",
            ["System.UInt16"] = "ushort",
            ["System.String"] = "string"
        };
        
        /// <summary>
        /// 生成QuicklyEntry
        /// </summary>
        /// <param name="assemblies">要扫描的程序集</param>
        /// <param name="result">生成结果回调（文件名-代码内容, 类型-程序集映射）</param>
        public static void GenerateQuickly(IEnumerable<Assembly> assemblies,
            Action<Dictionary<string, string>, Dictionary<Type, Assembly>> result)
        {
            var entryMethods = new List<(MethodInfo method, QuicklyEntryAttribute attr)>();
            var pathMap = new Dictionary<string, MethodInfo>();
            var classMethodMap = new Dictionary<string, Dictionary<string,MethodInfo>>(); // 用于存放每个类的方法
            var typeAssemblyMap = new Dictionary<Type, Assembly>();

            // 遍历程序集，查找所有带有 [QuicklyEntry] 的公共静态方法
            foreach (var assembly in assemblies)
            {
                foreach (var type in assembly.GetTypes())
                {
                    foreach (var method in type.GetMethods(BindingFlags.Public | BindingFlags.Static))
                    {
                        var attr = method.GetCustomAttribute<QuicklyEntryAttribute>();
                        if (attr != null)
                        {
                            if (string.IsNullOrEmpty(attr.Group)||string.IsNullOrEmpty(attr.ValueName))
                            {
                                //报错
                            }
                            
                            string nameChecker = attr.Group + "-" + attr.ValueName;
                            // 路径重复检查
                            if (pathMap.ContainsKey(nameChecker))
                            {
                                throw new InvalidOperationException(
                                    $"重复的 QuicklyEntry 路径: \"{nameChecker}\"");
                            }

                            entryMethods.Add((method, attr));
                            pathMap[nameChecker] = method;
                            typeAssemblyMap[type] = assembly;

                            // 存储到对应的 ClassName 类中
                            if (!classMethodMap.ContainsKey(attr.Group))
                            {
                                classMethodMap[attr.Group] = new Dictionary<string, MethodInfo>();
                            }

                            classMethodMap[attr.Group].Add(attr.ValueName,method);
                        }
                    }
                }
            }

            var fileContents = new Dictionary<string, string>();
            // 生成代码
            foreach (var group in classMethodMap)
            {
                var className = group.Key;
                
                var sb = new StringBuilder();
                sb.AppendLine("// <auto-generated/>");
                sb.AppendLine("// 自动生成的快速入口文件");
                sb.AppendLine("// 该文件由工具自动生成，请勿手动修改");
                sb.AppendLine();
                sb.AppendLine($"namespace LogicGamer.Quickly");
                sb.AppendLine("{");
                sb.AppendLine($"    public static class {className}");
                sb.AppendLine("    {");
                foreach (var item in group.Value)
                {
                    
                    var method = item.Value;
                    var attr = entryMethods.First(m => m.method == method).attr;
                    var fullTypeName = method.DeclaringType!.FullName!.Replace('+', '.'); // 支持嵌套类

                    if (!string.IsNullOrWhiteSpace(attr.Description))
                        sb.AppendLine($"        // Description: {attr.Description}");

                    // 如果是无参方法，则生成属性
                    if (method.GetParameters().Length == 0)
                    {
                        // 处理返回值类型，如果是泛型类型，需要获取其具体类型
                        string returnType = GetGenericTypeName(method.ReturnType);
                        sb.AppendLine($"        public static {returnType} {attr.ValueName} => {fullTypeName}.{method.Name}();");
                    }
                    else
                    {
                        // 如果是有参方法，则生成方法并记录参数
                        var parameters = method.GetParameters();
                        var parameterList = string.Join(", ", parameters.Select(p =>
                        {
                            // 处理泛型参数类型
                            string paramType = GetGenericTypeName(p.ParameterType);
                            return $"{paramType} {p.Name}";
                        }));

                        // 处理泛型方法名
                        string methodReturnType = GetGenericTypeName(method.ReturnType);
                        sb.AppendLine($"        public static {methodReturnType} {attr.ValueName}({parameterList}) => {fullTypeName}.{method.Name}({string.Join(", ", parameters.Select(p => p.Name))});");
                    }
                }
                sb.AppendLine("    }");
                sb.AppendLine("}");

                fileContents["Quickly"+'.'+className] = sb.ToString();
            }

            // 返回生成的代码内容和类型-程序集映射
            result?.Invoke(fileContents, typeAssemblyMap);
        }

        private static string GetGenericTypeName(Type type)
        {
            if (TypeAliases.TryGetValue(type.FullName!, out var alias))
            {
                return alias;
            }

            if (type.IsGenericType)
            {
                string baseTypeName = type.GetGenericTypeDefinition().FullName!;
                baseTypeName = baseTypeName.Substring(0, baseTypeName.IndexOf('`'));

                string[] typeArguments = type.GetGenericArguments()
                    .Select(GetGenericTypeName)
                    .ToArray();

                return $"{baseTypeName}<{string.Join(", ", typeArguments)}>";
            }

            return type.FullName!;
        }


    }
}
