using LogicGamer.Core.Engine;
using LogicGamer.Core.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Text;

namespace LogicGamer.Core
{
    public static class GeneratorTool 
    {
        /// <summary>
        /// 生成一个Quickly(manager的快速入口)文件
        /// </summary>
        /// <param name="assemblies">要扫描的程序集</param>
        /// <param name="result">生成结果回调（代码内容, 类型-程序集映射）</param>
        public static void GenerateQuickly(IEnumerable<Assembly> assemblies, Action<string, Dictionary<Type, Assembly>> result)
        {
            // 1. 扫描所有实现了IEngine的类型
            var engineTypes = Utility.Type.GetTypesImplementing<IEngine>()
                .ToDictionary(type => type, type => type.Assembly);

            // 2. 生成代码模板
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("// 自动生成的快速入口文件");
            sb.AppendLine("// 该文件由工具自动生成，请勿手动修改");
            sb.AppendLine("namespace LogicFramework.Generate");
            sb.AppendLine("{");
            sb.AppendLine("    public static class Quickly");
            sb.AppendLine("    {");

            // 3. 为每个Engine类型生成属性
            foreach (var kvp in engineTypes)
            {
                var type = kvp.Key;
                var typeName = type.Name;
                var propertyName = typeName;
                sb.AppendLine($"        public static {typeName} {propertyName} => Logic.GetEngine<{typeName}>();");
            }
            sb.AppendLine("    }");
            sb.AppendLine("}");

            // 4. 返回结果
            result?.Invoke(sb.ToString(), engineTypes);
        }
    }
}
