using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Text;
using LogicGamer.Core.Attributes;

namespace LogicGamer.Core
{
    public static  class GeneratorTool
    {
        /// <summary>
        /// 生成一个()Quickly(manager的快速入口))文件
        /// </summary>
        /// <param name="assemblies">要扫描的程序集</param>
        /// <param name="result">生成结果回调（代码内容, 类型-程序集映射）</param>
        public static void GenerateQuickly(IEnumerable<Assembly> assemblies,
            Action<Dictionary<string, string>, Dictionary<Type, Assembly>> result)
        {
            var entryMethods = new List<(MethodInfo method, QuicklyEntryAttribute attr)>();
            var pathMap = new Dictionary<string, MethodInfo>();
            var classMethodMap = new Dictionary<string, List<string>>(); // 用于存放每个类的方法
            var typeAssemblyMap = new Dictionary<Type, Assembly>();

            // 遍历程序集，查找所有带有 [QuicklyEntry] 的公共静态方法
            foreach (var assembly in assemblies)
            {
                foreach (var type in assembly.GetTypes())
                {
                    foreach (var method in type.GetMethods(BindingFlags.Public | BindingFlags.Static))
                    {
                        var attr = method.GetCustomAttribute<QuicklyEntryAttribute>();
                        if (attr != null)
                        {
                            if (string.IsNullOrEmpty(attr.Group)||string.IsNullOrEmpty(attr.ValueName))
                            {
                                //报错
                            }
                            
                            string nameChecker = attr.Group + "-" + attr.ValueName;
                            // 路径重复检查
                            if (pathMap.ContainsKey(nameChecker))
                            {
                                throw new InvalidOperationException(
                                    $"重复的 QuicklyEntry 路径: \"{nameChecker}\"");
                            }

                            entryMethods.Add((method, attr));
                            pathMap[nameChecker] = method;
                            typeAssemblyMap[type] = assembly;

                            // 存储到对应的 ClassName 类中
                            if (!classMethodMap.ContainsKey(attr.Group))
                            {
                                classMethodMap[attr.Group] = new List<string>();
                            }

                            classMethodMap[attr.Group].Add(method.Name);
                        }
                    }
                }
            }

            var fileContents = new Dictionary<string, string>();
            // 生成代码
            foreach (var className in classMethodMap.Keys)
            {
                var sb = new StringBuilder();
                sb.AppendLine("// <auto-generated/>");
                sb.AppendLine("// 自动生成的快速入口文件");
                sb.AppendLine("// 该文件由工具自动生成，请勿手动修改");
                sb.AppendLine();
                sb.AppendLine($"namespace LogicFramework.Generate");
                sb.AppendLine("{");
                sb.AppendLine($"    public static partial class QuicklyEntry");
                sb.AppendLine("    {");
                sb.AppendLine($"        public static class {className}");
                foreach (var methodName in classMethodMap[className])
                {
                    var method = entryMethods.First(m => m.method.Name == methodName).method;
                    var attr = entryMethods.First(m => m.method.Name == methodName).attr;
                    var fullTypeName = method.DeclaringType!.FullName!.Replace('+', '.'); // 支持嵌套类
                    var safeMethodName = $"{method.DeclaringType.Name}_{methodName}"; // 避免重名

                    if (!string.IsNullOrWhiteSpace(attr.Description))
                        sb.AppendLine($"        // Description: {attr.Description}");

                    // 如果是无参方法，则生成属性
                    if (method.GetParameters().Length == 0)
                    {
                        sb.AppendLine(
                            $"        public static {fullTypeName} {safeMethodName} => {fullTypeName}.{methodName}();");
                    }
                    else
                    {
                        // 如果是有参方法，则生成方法并记录参数
                        var parameters = method.GetParameters();
                        var parameterList =
                            string.Join(", ", parameters.Select(p => $"{p.ParameterType.Name} {p.Name}"));
                        sb.AppendLine(
                            $"        public static void {safeMethodName}({parameterList}) => {fullTypeName}.{methodName}({string.Join(", ", parameters.Select(p => p.Name))});");
                    }
                }

                sb.AppendLine("    }");
                sb.AppendLine("}");

                fileContents[className] = sb.ToString();
            }

            // 返回生成的代码内容和类型-程序集映射
            result?.Invoke(fileContents, typeAssemblyMap);
        }


    }
}
